spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  redis:
    host: localhost
    port: 6379
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
jwt:
  secret: ulZPbEorpFDWFhbjoKitChJUFM2uUijkZt8q39bu7OUDklJ862TEtHHj2GKcQTxnDLNf4nBwI23I4qFHgTJPbwiK5xKsebRNfvFJ0R6cxe9jgNyZ8ffkVR6SODXmb1Dq
  access: 3600000
  refresh: 1209600000

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: { SMTP_EMAIL }
#    password: { SMTP_PASSWORD }
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#          auth: true
logging:
  level:
    org.hibernate.SQL: debug