spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${ACTIVE_PROFILES}
  application:
    name: module-api

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
jwt:
  secret: ${JWT_SECRET}
  access: ${JWT_ACCESS_EXPIRATION}
  refresh: ${JWT_REFRESH_EXPIRATION}

# SMTP
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: { SMTP_EMAIL }
#    password: { SMTP_PASSWORD }
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#          auth: true

#properties
#props:
#  reset-password-url: {프론트 배포 서버 url}

logging:
  level:
    org.hibernate.SQL: debug

---

spring:
  config:
    activate:
      on-profile: release

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: info